name: CI

on:
  pull_request_target:
  push:
    branches: main
    paths:
      - .github/workflows/main.yml
      - pyproject.toml
      - uv.lock
      - '**.py'

jobs:
  python:
    uses: winstxnhdw/actions/.github/workflows/uv.yml@main
    with:
      disable-test: true
